# Generated by Django 5.2.8 on 2025-11-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_bout_author_about_alter_member_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='fine',
            new_name='Cost',
        ),
        migrations.RemoveField(
            model_name='book',
            name='descipion',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
