# Generated by Django 5.2.8 on 2025-11-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_fine_borrowing_cost_remove_book_descipion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcop',
            name='un_id',
            field=models.IntegerField(unique=True),
        ),
    ]
