# Generated by Django 5.2.8 on 2025-11-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bookcop_un_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='Bookcop',
            new_name='bookcop',
        ),
    ]
