# Generated by Django 5.2.8 on 2025-11-30 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_bookcop_borrowing_bookcop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='bookcop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bookcop'),
        ),
    ]
