# Generated by Django 5.2.8 on 2025-11-30 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_borrowing_bookcop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='bookcop',
            new_name='Bookcop',
        ),
    ]
