# Generated by Django 5.2.8 on 2025-11-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_borrowing_bookcop_borrowing_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='book',
        ),
        migrations.CreateModel(
            name='Bookcop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('un_id', models.IntegerField(unique=True)),
                ('is_av', models.BooleanField(default=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
            ],
        ),
        migrations.AddField(
            model_name='borrowing',
            name='bookcop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bookcop'),
        ),
    ]
