# Generated by Django 5.2.8 on 2025-11-30 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_borrowing_book_bookcop_borrowing_bookcop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowing',
            name='bookcop',
        ),
        migrations.AddField(
            model_name='borrowing',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.book'),
        ),
        migrations.DeleteModel(
            name='Bookcop',
        ),
    ]
