# Generated by Django 5.2.8 on 2025-12-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_pub',
            field=models.DateField(null=True),
        ),
    ]
