# Generated by Django 5.2.8 on 2025-12-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/member'),
        ),
    ]
