# Generated by Django 5.2.8 on 2025-12-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_member_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='categ',
            field=models.ManyToManyField(related_name='books', to='main.category'),
        ),
    ]
